name: Deploy GitHub Pages

on:
  push:
    branches:
      - main   # твоя основная ветка

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Берём файлы из репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # корень репозитория, где index.html
